#markdown: rdiscount
permalink: /:title/
url: http://qingping209.github.io
highlighter: pygments
highlighter: rouge
paginate: 100
paginate_path: "page:num"
name: cnredis
author: qingping209
email: paralleld@qq.com
hub: qingping209
safe: false
intensedebate_identifier: 40lcPvGHztdOZzuQmbIE
plugins: [jekyll-paginate]
gems: [jekyll-paginate]
